sudo: required
dist: trusty
language: cpp
compiler: gcc

install:
  - wget https://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run
  - chmod +x qt-opensource-linux-x64-5.9.1.run
  
script:
  - mkdir build
  - cd build
  - qmake ../src/versa-tile.pro
  - make -B
